engines:
  csslint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  radon:
    enabled: true
ratings:
   paths:
   - "lib/*"
   - "spec/*"
   - "styles/*"
   - "*.html"
   - "*.js"
   - "*.json"
exclude_paths:
- "node_modules/*"
